[package]
name = "vigem-client"
version = "0.1.0"
authors = ["PurpleMyst <PurpleMyst@users.noreply.github.com>"]
edition = "2018"

[dependencies]
bitflags = "1.3.2"
thiserror = "1.0.26"
vigem-client-sys = { path = "../vigem-client-sys" }
